### ISSUE TITLE
random.sample line 132 and np.sum(idx) line 133 

### ISSUE THREAD

**Issue by GCMusto** [sigmaquadro/VolatilityEstimator#1]
Very nice work! However, I could not run the code as it is:

-  On line 132 for the first argument of random.sample I had to embed the indexes of the array ret in a list;
- On  line 133 using `np.sum(idx)` returns an array whose dimensions are incompatible with the expected number of jumps (10% of 200). I replaced `np.sum(idx)` with `len(idx)`; 

Kind regards,
Giancarlo

**Comment by sigmaquadro** [comment]
Many thanks for pointing out that. We implemented the suggested fixings  in a new commit.
